// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj44PoLFjKuc74v_no_OCXmpRuhAlWGWs',
    appId: '1:251265767014:web:0a3e60d9ddf8d90a89ffa7',
    messagingSenderId: '251265767014',
    projectId: 'novanet-vpn',
    authDomain: 'novanet-vpn.firebaseapp.com',
    storageBucket: 'novanet-vpn.appspot.com',
    measurementId: 'G-58E6YWVN7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCun62JNYV68UckDQNPowrzA4jsgLnLuHY',
    appId: '1:251265767014:android:949fa89b6a94a3b889ffa7',
    messagingSenderId: '251265767014',
    projectId: 'novanet-vpn',
    storageBucket: 'novanet-vpn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABogfu8mKC1XVzJ4zcIiTRFx2m0zfSIYU',
    appId: '1:251265767014:ios:7668b8532648c0b889ffa7',
    messagingSenderId: '251265767014',
    projectId: 'novanet-vpn',
    storageBucket: 'novanet-vpn.appspot.com',
    iosBundleId: 'com.example.novanetVpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABogfu8mKC1XVzJ4zcIiTRFx2m0zfSIYU',
    appId: '1:251265767014:ios:7668b8532648c0b889ffa7',
    messagingSenderId: '251265767014',
    projectId: 'novanet-vpn',
    storageBucket: 'novanet-vpn.appspot.com',
    iosBundleId: 'com.example.novanetVpn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj44PoLFjKuc74v_no_OCXmpRuhAlWGWs',
    appId: '1:251265767014:web:3c36b028ce42c52789ffa7',
    messagingSenderId: '251265767014',
    projectId: 'novanet-vpn',
    authDomain: 'novanet-vpn.firebaseapp.com',
    storageBucket: 'novanet-vpn.appspot.com',
    measurementId: 'G-LTTKH5M6MQ',
  );
}
